version: '2.2'

services:
  valley:
    build: docker
    container_name: stardew
    environment:
      - "VNC_PASSWORD=nyanyanya"
      - "DISPLAY_HEIGHT=900"
      - "DISPLAY_WIDTH=1200"
    ports:
      # VNC
      - 5902:5900
      # NO-VNC WEB
      - 5801:5800
      # Game
      - 24642:24642/udp
    volumes:
      - ./valley_saves:/config/xdg/config/StardewValley/Saves
      - ./docker/mods/:/data/mods/
